name: renmoney_weatherapp
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  dio: ^5.3.3
  get_it: ^7.6.3
  provider: ^6.1.2
  # flutter_secure_storage: ^9.0.0
  flutter_secure_storage: ^9.2.2
  bot_toast: ^4.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  logging: ^1.2.0
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.24.3 
  mockito: ^5.4.4
  build_runner:
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/renmoney_launcher.png
  color: "#FFFFFF"
  android: true
  ios: true

flutter_launcher_icons:
  android: "weather_icon"
  ios: true
  image_path: "assets/images/renmoney_launcher.png"
  adaptive_icon_background: "#FFFFFF"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/cityList.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
